expname: carla_256_clip_s1_embed128
data:
  imsize: 256
  datadir: /gdata1/zhangkd/NeRF/carla/images
  type: carla
  radius: 10.
  near: 7.5
  far: 12.5
  fov: 30.0
training:
  outdir: /gdata2/zhangkd/nerf/graf/carla_256_clip_s1_embed128
  batch_size: 4
nerf:
  N_importance: 0
  embed_dim: 128
  finetune_codes: False